/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package entradas;

/**
 *
 * @author pc
 */
public class registros extends javax.swing.JFrame {

    /**
     * Creates new form registros
     */
    public registros() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
                this.setSize(390, 450);

        getRootPane().setDefaultButton(buttonadmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        mec = new javax.swing.JLabel();
        elec = new javax.swing.JLabel();
        eleca = new javax.swing.JLabel();
        civ = new javax.swing.JLabel();
        sis = new javax.swing.JLabel();
        quim = new javax.swing.JLabel();
        ind = new javax.swing.JLabel();
        ges = new javax.swing.JLabel();
        inf = new javax.swing.JLabel();
        doc = new javax.swing.JLabel();
        ext = new javax.swing.JLabel();
        meca = new javax.swing.JTextField();
        admon = new javax.swing.JTextField();
        elect = new javax.swing.JTextField();
        electro = new javax.swing.JTextField();
        info = new javax.swing.JTextField();
        doce = new javax.swing.JTextField();
        sist = new javax.swing.JTextField();
        civil = new javax.swing.JTextField();
        indus = new javax.swing.JTextField();
        gest = new javax.swing.JTextField();
        exter = new javax.swing.JTextField();
        quimi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        maes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        doct = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buttonadmin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        administra = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jButton5.setText("jButton1");

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin.setText("Administración");
        jPanel2.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 27, -1, -1));

        mec.setText("Mecánica");
        jPanel2.add(mec, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 68, -1, -1));

        elec.setText("Eléctrica");
        jPanel2.add(elec, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 118, -1, -1));

        eleca.setText("Electrónica");
        jPanel2.add(eleca, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 175, -1, -1));

        civ.setText("Civil");
        jPanel2.add(civ, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 220, -1, -1));

        sis.setText("Sistemas");
        jPanel2.add(sis, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 261, -1, -1));

        quim.setText("Química");
        jPanel2.add(quim, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        ind.setText("Industrial");
        jPanel2.add(ind, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        ges.setText("Gestión");
        jPanel2.add(ges, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        inf.setText("Informática");
        jPanel2.add(inf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        doc.setText("Docentes");
        jPanel2.add(doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        ext.setText("Externos");
        jPanel2.add(ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        jPanel2.add(meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 65, 41, -1));
        jPanel2.add(admon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 41, -1));
        jPanel2.add(elect, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 115, 41, -1));
        jPanel2.add(electro, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 172, 41, -1));
        jPanel2.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 41, -1));
        jPanel2.add(doce, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 41, -1));
        jPanel2.add(sist, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 41, -1));
        jPanel2.add(civil, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 217, 41, -1));
        jPanel2.add(indus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 41, -1));
        jPanel2.add(gest, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 41, -1));
        jPanel2.add(exter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 41, -1));
        jPanel2.add(quimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 41, -1));

        jLabel1.setText("Maestria");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        jPanel2.add(maes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 40, -1));

        jLabel2.setText("Doctorado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));
        jPanel2.add(doct, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 40, -1));

        jButton1.setText("Gráficas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        buttonadmin.setText("Registrar");
        buttonadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonadminActionPerformed(evt);
            }
        });
        jPanel2.add(buttonadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jButton2.setText("Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jLabel3.setText("Administrativos");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));
        jPanel2.add(administra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 40, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 400));

        jMenu2.setText("Modificar");

        jMenuItem2.setText("Registros");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonadminActionPerformed
 System.out.println(admon.getText());
 insertar in=new insertar();
 in.insert(1, admon.getText());
 in.insert(2, meca.getText());
  in.insert(3, elect.getText());
  in.insert(4, electro.getText());
 in.insert(5, civil.getText());
  in.insert(6, sist.getText());
  
  in.insert(7, info.getText());
 in.insert(8, doce.getText());
  in.insert(9, gest.getText());
  in.insert(10, exter.getText());
in.insert(11, indus.getText());
  in.insert(12, quimi.getText());
   in.insert(13, maes.getText());
    in.insert(14, doct.getText());
    in.insert(15, administra.getText()); 
  quimi.setText("");
  indus.setText("");
  exter.setText("");
  gest.setText("");
  doce.setText("");
  info.setText("");
  
  sist.setText("");
  civil.setText("");
  electro.setText("");
  elect.setText("");
  meca.setText("");
  admon.setText("");
  maes.setText("");
  doct.setText("");
  administra.setText("");
  
    }//GEN-LAST:event_buttonadminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new Graficas().iniciar();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new tablas().mostrar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
new RegistrosEdit().iniciar();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void principal() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registros().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JTextField administra;
    private javax.swing.JTextField admon;
    private javax.swing.JButton buttonadmin;
    private javax.swing.JLabel civ;
    private javax.swing.JTextField civil;
    private javax.swing.JLabel doc;
    private javax.swing.JTextField doce;
    private javax.swing.JTextField doct;
    private javax.swing.JLabel elec;
    private javax.swing.JLabel eleca;
    private javax.swing.JTextField elect;
    private javax.swing.JTextField electro;
    private javax.swing.JLabel ext;
    private javax.swing.JTextField exter;
    private javax.swing.JLabel ges;
    private javax.swing.JTextField gest;
    private javax.swing.JLabel ind;
    private javax.swing.JTextField indus;
    private javax.swing.JLabel inf;
    private javax.swing.JTextField info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField maes;
    private javax.swing.JLabel mec;
    private javax.swing.JTextField meca;
    private javax.swing.JLabel quim;
    private javax.swing.JTextField quimi;
    private javax.swing.JLabel sis;
    private javax.swing.JTextField sist;
    // End of variables declaration//GEN-END:variables
}
